[project]
name = "backend"
version = "0.1.0"
description = "Backend za Nogometni klub - demo aplikacija bez baze podataka (podaci se drze u memoriji)"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi[standard]>=0.115.0",
    "pyjwt>=2.8.0",
]

[tool.fastapi]
entrypoint = "main:app"
